# Change these first
owner: WindReserve # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: WindReserve Website
    icon: https://windreserve.de/wp-content/uploads/2019/06/windreserve-favicon-90x90.png?x79943
    url: https:/windreserve.de
  - name: Cloud
    url: https://cloud.windreserve.de
    icon: https://nextcloud.com/wp-content/themes/next/assets/img/common/favicon.png?x53054
  - name: Wiki
    url: https://wiki.windreserve.de
    icon: https://js.wiki/favicon.ico
  - name: Craftnote
    url: https://app.mycraftnote.de
    icon: https://www.craftnote.de/assets/images/favicon.ico
  - name: Strato Webmail
    url: https://webmail.strato.de/appsuite/signin#!!&app=io.ox/mail&folder=default0/INBOX
    icon: https://webmail.strato.com/appsuite/v=7.10.5-27.20211215.100957/apps/themes/default/favicon.ico
  - name: Element
    url: https://element.windreserve.de
    icon: https://element.windreserve.de/vector-icons/favicon.ico
  - name: Inventory
    url: https://inventory.windreserve.de
    icon: https://snipeitapp.com/img/icons/favicon.ico
  - name: Grafana
    url: https://grafana.windreserve.de
    icon: https://grafana.com/static/assets/img/fav32.png
  - name: Alertmanager
    url: https://alertmanager.windreserve.de
    icon: https://prometheus.io/assets/favicons/favicon.ico
  - name: Matomo
    url: https://matomo.windreserve.de
    icon: https://css-tricks.com/wp-content/uploads/2019/09/DefaultIcon.png
  - name: Synapse Admin
    url: https://matrix.windreserve.de/synapse-admin
    icon: https://element.windreserve.de/vector-icons/favicon.ico
 # - name: Test Broken Site
 #   url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.windreserve.de
  # baseUrl: /status
  logoUrl: https://cloud.windreserve.de/s/tsFGAezfnDDcZTb/preview
  name: WindReserve Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: Aktive Störungen
  allSystemsOperational: All systems are operational
  incidentReport: "Störung #$NUMBER Report →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS posts
  incidentTitle: Störung $NUMBER Details
  incidentDetails: Störungsdetails
  incidentFixed: Behoben
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentViewOnGitHub: Auf GitHub Ansehen
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Zurück zu allen Störungen
  pastIncidents: Vergangene Störungen
  pastIncidentsResolved: Behoben in $MINUTES minuten mit $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response time (ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Lädt
  navGitHub: GitHub
  footer: Diese Seite ist[open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit überschritten
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Token löschen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler is aufgetreten
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: Versuche es in ein paar Minuten nochmal.
  errorHome: Zurück zur Homepage
  pastScheduledMaintenance: Vergangene Wartungsarbeiten
  scheduledMaintenance: Geplante Wartungsarbeiten
  scheduledMaintenanceSummaryStarted: Begann am $DATE für eine Dauer von $DURATION minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für eine Dauer von $DURATION minuten
  startedAt: Begann um
  startsAt: Beginnt um
  duration: Dauer
  durationMin: $DURATION minuten
  incidentCompleted: Beendet
  incidentScheduled: Geplant
